!> Emits docs/user/registry.md from the doc-only registry (run from the repo root).
!> Optional argv(1) overrides the output path — used by the `registry-docs` ctest gate
!> to regenerate into the build tree and diff against the tracked file.
program IGLOO_docgen
  use IGLOO_Register,       only: Register_IGLOO_Params
  use IGLOO_Input_Registry, only: reg
  implicit none
  character(len=1024) :: outfile
  integer :: nargs

  call Register_IGLOO_Params()

  nargs = command_argument_count()
  if (nargs >= 1) then
    call get_command_argument(1, outfile)
  else
    outfile = 'docs/user/registry.md'
  end if

  call reg%generate_markdown(trim(outfile), &
    intro='Solver-owned `input.ini` sections, auto-generated by `DocGen` from the doc-only '// &
          'registry (`src/lib/config/Register_IGLOO.f90`; runtime reader: `Lib_INI.f90`). '// &
          'Phase and boundary sections (`[GPB-Phase*]`, `[BCB-Block*]`) are '// &
          'ATLAS-generated and described in [Input File](input.md).')

end program IGLOO_docgen
